package Vista;

import ConexionDB.Conexion;
import Modelo.CifradoHash;
import Modelo.MetodoUsuario;
import Modelo.SQLConsultas;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author tboss
 */
public class Altausuario extends javax.swing.JFrame {

    /**
     * Creates new form Altausuario
     */
    Login log = new Login();

    public Altausuario() {
        initComponents();
        this.setResizable(true);
        this.setLocationRelativeTo(this);
    }

    public void limpiarForm() {
        // una vez introducido los datos se limiara nuestro formulario
        txt_nombreuser.setText("");
        txt_apellidosuser.setText("");
        txt_emailuser.setText("");
        txt_passuser.setText("");
        txt_passConfrimacion.setText("");
        txt_telefonouser.setText("");
        txt_direccionuser.setText("");
    }

    // validacion de los datos a la hora del registro
    public boolean comprobacionCorrecto() {
        //copiamos la varibale de arriba, en caso de que el contenido se encuentre vacio nos lo especificara medainte un JOptionPane
        String name = txt_nombreuser.getText();
        String apellido = txt_apellidosuser.getText();
        String pass = txt_passuser.getText();
        String email = txt_emailuser.getText();
        String contact = txt_telefonouser.getText();
        //Selecionamos las celadas en caso de que queden vacias, se indicara un error 
        if (name.equals("")) {
            JOptionPane.showMessageDialog(this, "El contenido del nombre no esta relleno \n porfavor introduzca su nombre");
            return false;
        }
        if (apellido.equals("")) {
            JOptionPane.showMessageDialog(this, "El contenido del apellido se encuentra vacio \n porfavor introduzca su apellido");
            return false;
        }
        if (pass.equals("")) {
            JOptionPane.showMessageDialog(this, "El contenido del contraseña no esta relleno \n porfavor introduzca su contraseña - password");
            return false;
        }
        if (email.equals("") || !email.matches("^.+@.+\\..+$")) {
            JOptionPane.showMessageDialog(this, "El contenido del email no esta relleno \n o no corresponde con un correo, debe tener una terminacion en @gmail.com, @hotmail.es etc");
            return false;
        }
        if (contact.equals("")) {
            JOptionPane.showMessageDialog(this, "El contenido del contacto no esta relleno \n porfavor introduzca su numero de contacto");
            return false;
        }

        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPBackground = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_nombreuser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_emailuser = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_passuser = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        txt_apellidosuser = new javax.swing.JTextField();
        txt_telefonouser = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        bGuardarUser = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jBvolverLogin = new javax.swing.JButton();
        txt_direccionuser = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_passConfrimacion = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPBackground.setForeground(new java.awt.Color(0, 0, 0));
        jPBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(1234, 680));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0,0,0, 180));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGAPP/icons8-user-64.png"))); // NOI18N
        jLabel1.setText("Nombre");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 160, -1));

        txt_nombreuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreuserActionPerformed(evt);
            }
        });
        jPanel3.add(txt_nombreuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 290, 40));

        jLabel3.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGAPP/icons8-email-64.png"))); // NOI18N
        jLabel3.setText("Correo electronico ");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 270, -1));

        txt_emailuser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_emailuserFocusLost(evt);
            }
        });
        txt_emailuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailuserActionPerformed(evt);
            }
        });
        jPanel3.add(txt_emailuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 290, 39));

        jLabel5.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGAPP/icons8-password-64.png"))); // NOI18N
        jLabel5.setText("Contraseña");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 210, -1));
        jPanel3.add(txt_passuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 290, 39));

        jLabel2.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGAPP/icons8-user-64.png"))); // NOI18N
        jLabel2.setText("Apellidos");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 190, -1));
        jPanel3.add(txt_apellidosuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 290, 39));

        txt_telefonouser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_telefonouserKeyTyped(evt);
            }
        });
        jPanel3.add(txt_telefonouser, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 290, 39));

        jLabel7.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGAPP/icons8-phone-64.png"))); // NOI18N
        jLabel7.setText("Teléfono");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 220, -1));

        bGuardarUser.setText("Guardar usuario");
        bGuardarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarUserActionPerformed(evt);
            }
        });
        jPanel3.add(bGuardarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, 240, -1));

        jLabel6.setFont(new java.awt.Font("LCDMono2", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 255, 255));
        jLabel6.setText("Crear Usuario");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 19, 335, 48));

        jBvolverLogin.setText("Volver al Login");
        jBvolverLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBvolverLoginActionPerformed(evt);
            }
        });
        jPanel3.add(jBvolverLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 540, 130, -1));
        jPanel3.add(txt_direccionuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 640, 39));

        jLabel8.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGAPP/icons8-house-64.png"))); // NOI18N
        jLabel8.setText("Dirección: Ciudad, calle de su casa y número");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 570, -1));
        jPanel3.add(txt_passConfrimacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, 290, 39));

        jLabel9.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGAPP/icons8-password-64.png"))); // NOI18N
        jLabel9.setText("Confirmar Contraseña");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 290, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 940, 600));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/computer-g255464949_1280.jpg"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 780));

        jPBackground.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 770));

        getContentPane().add(jPBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -4, 1250, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_emailuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailuserActionPerformed

    private void bGuardarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarUserActionPerformed
        // TODO add your handling code here:
        // realizamos una insercion por llamada de metodos 
        Modelo.SQLConsultas modSql = new SQLConsultas();
        Modelo.MetodoUsuario modUser = new MetodoUsuario();
        //si nuestro metodo insercion de datos esta correcto procedemos a comprobar las contraseñas
        if (comprobacionCorrecto() == true) {
            // comprobamos el contendio de las 2 contraseñas
            String pass = new String(txt_passuser.getPassword());
            String passConfirmar = new String(txt_passConfrimacion.getPassword());
            // si son iguales continua
            if (pass.equals(passConfirmar)) {
                // comprobamos de que no se repitan los correos, entendemos que los nombres si se pueden repetir
                if (modSql.existeUser(txt_emailuser.getText()) == 0) {
                    // creamos una variable donde le pasaremos la contraseña almacenada
                    //String nuevaContra = CifradoHash.sha1(pass); 
                    String nuevaContra = pass;

                    System.out.println(nuevaContra);
                    modUser.setNombre(txt_nombreuser.getText());
                    modUser.setApellidos(txt_apellidosuser.getText());
                    modUser.setEmail(txt_emailuser.getText());
                    modUser.setPass(nuevaContra);
                    modUser.setTelefono(txt_telefonouser.getText());
                    modUser.setDireccioncasa(txt_direccionuser.getText());
                    // le indicamos que el usuario sera tipo 2 osea cliente
                    modUser.setTipo(2);
                    // si el metodo registrar usuario esta todo correcto se procedera a limirar el formulario y ya dispondremos de nuetsra cuenta
                    if (modSql.registrarUser(modUser)) {
                        JOptionPane.showMessageDialog(null, "Usuario creado");
                        limpiarForm();
                    } else {
                        JOptionPane.showMessageDialog(null, "No se ha podido guardar");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Ese correo ya esta en uso");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");
            }
        } else {
            System.out.println("datos no introducidos");
        }
    }//GEN-LAST:event_bGuardarUserActionPerformed

    private void txt_emailuserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emailuserFocusLost

    }//GEN-LAST:event_txt_emailuserFocusLost

    private void txt_nombreuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreuserActionPerformed

    private void jBvolverLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBvolverLoginActionPerformed
        // TODO add your handling code here:
        //volver al login
        Login l = new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBvolverLoginActionPerformed

    private void txt_telefonouserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telefonouserKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();

        boolean numbero = key >= 48 && key <= 57;
        if (!numbero) {
            evt.consume();
        }
        if (txt_telefonouser.getText().length() >= 9) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_telefonouserKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Altausuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Altausuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Altausuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Altausuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Altausuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bGuardarUser;
    private javax.swing.JButton jBvolverLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPBackground;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txt_apellidosuser;
    private javax.swing.JTextField txt_direccionuser;
    private javax.swing.JTextField txt_emailuser;
    private javax.swing.JTextField txt_nombreuser;
    private javax.swing.JPasswordField txt_passConfrimacion;
    private javax.swing.JPasswordField txt_passuser;
    private javax.swing.JTextField txt_telefonouser;
    // End of variables declaration//GEN-END:variables
}
