package Vista;

import Modelo.CifradoHash;
import Modelo.MetodoUsuario;
import Modelo.SQLConsultas;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import jdk.internal.org.objectweb.asm.tree.analysis.Value;

/**
 *
 * @author tboss
 */
public class Login extends javax.swing.JFrame {

    
    public Login() {
        initComponents();
        this.setResizable(true);
        this.setLocationRelativeTo(this);
        // quitando las porpiedades del boton para que solo se vea la imagen
        jBLogin.setOpaque(false);
        jBLogin.setContentAreaFilled(false);
        jBLogin.setBorderPainted(false);
    }
    
    int logId = 0;
    int datousuario = 0;
    //String correo;

    // nos encargamso de que el usuario rellene todos los datos necesarios para logear
    public boolean validateLogin() {
        String email = txt_correo.getText();
        String pass = txt_password.getText();
        //comprobamos que los contenidos de que no esten vacios

        if (email.equals("")) {
            JOptionPane.showMessageDialog(this, "Profavor introduzca su correo electronico");
            return false;
        }
        if (pass.equals("")) {
            JOptionPane.showMessageDialog(this, "Porfavor introduzca su contraseña");
            return false;
        }
        return true;
    }

    // comprobacion de cuenta existente, y si son los mismos carracteres 
    public void login() {

        String email = txt_correo.getText();
        String pass = new String(txt_password.getPassword());
        String nombreuse, apelldiouser, correo;
        int tipous = 0;
        //realizamos una conexion a nuestra base de datos

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/log", "root", "");
            //realizamos una selecion en nuestra tabla usuarios donde el email y contraseña corresponda con lo que coincidan 
            PreparedStatement pst = con.prepareStatement("select * from user where email = ? and pass = ?");

            pst.setString(1, email);
            pst.setString(2, pass);

            // comparamos la ejecucion de los datos intorducidos con los de nuestra base de datos
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                IdLogeador.setText(rs.getString("id_user"));
                tipous = rs.getInt("tipo");
                nombreuse = rs.getString("nombre");
                apelldiouser = rs.getString("apellidos");

                if (tipous == 1) {
                    AdminPanel a = new AdminPanel();
                    a.setVisible(true);
                    this.dispose();
                    JOptionPane.showMessageDialog(this, "Bienvenido Administrador@\n " + nombreuse + " " + apelldiouser);
                } else {
                    // si esos datos existen 
                    JOptionPane.showMessageDialog(this, "Bienvenido usuari@\n" + nombreuse + " " + apelldiouser);
                    // se procede a visualizar el panel principal
                    logId= Integer.parseInt(IdLogeador.getText());
                    Home hom = new Home(logId);
                    // idUsuarioLogueado = IdLogeador.getText()
                    hom.setVisible(true);
                    this.dispose();
                    
                }
            } else {
                JOptionPane.showMessageDialog(this, "Error, datos no correctos");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void guardarElIdDeMiUsuario(String usuario) {
        txt_correo.setText(usuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPizquierda = new javax.swing.JPanel();
        txt_correo = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        jPImagenLateral = new javax.swing.JPanel();
        jLSalir = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_log_pass = new javax.swing.JLabel();
        lbl_log_email = new javax.swing.JLabel();
        jBLogin = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        IdLogeador = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPizquierda.setBackground(new java.awt.Color(255, 255, 255));

        txt_correo.setBackground(new java.awt.Color(255, 255, 255));
        txt_correo.setForeground(new java.awt.Color(153, 153, 153));
        txt_correo.setText("Introduce tu correo");
        txt_correo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_correoMousePressed(evt);
            }
        });

        txt_password.setBackground(new java.awt.Color(255, 255, 255));
        txt_password.setForeground(new java.awt.Color(153, 153, 153));
        txt_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_passwordMousePressed(evt);
            }
        });
        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });

        jPImagenLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLSalir.setFont(new java.awt.Font("Courier New", 0, 48)); // NOI18N
        jLSalir.setForeground(new java.awt.Color(0, 0, 0));
        jLSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLSalir.setText("X");
        jLSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLSalirMouseEntered(evt);
            }
        });
        jPImagenLateral.add(jLSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 60, 50));

        jLabel4.setFont(new java.awt.Font("MS Gothic", 3, 150)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ORSTED");
        jPImagenLateral.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 520, 150));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/ITLogin.jpg"))); // NOI18N
        jPImagenLateral.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 680));

        lbl_log_pass.setFont(new java.awt.Font("MS Gothic", 0, 24)); // NOI18N
        lbl_log_pass.setForeground(new java.awt.Color(0, 0, 0));
        lbl_log_pass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGAPP/icons8-password-64.png"))); // NOI18N
        lbl_log_pass.setText("Contraseña");

        lbl_log_email.setFont(new java.awt.Font("MS Gothic", 0, 24)); // NOI18N
        lbl_log_email.setForeground(new java.awt.Color(0, 0, 0));
        lbl_log_email.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGAPP/icons8-email-64.png"))); // NOI18N
        lbl_log_email.setText("Introduce tu correo");

        jBLogin.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jBLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/img_login.png"))); // NOI18N
        jBLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLoginActionPerformed(evt);
            }
        });

        jButton1.setText("Crear Usuario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPizquierdaLayout = new javax.swing.GroupLayout(jPizquierda);
        jPizquierda.setLayout(jPizquierdaLayout);
        jPizquierdaLayout.setHorizontalGroup(
            jPizquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPizquierdaLayout.createSequentialGroup()
                .addGroup(jPizquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPizquierdaLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPizquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_password, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                            .addComponent(txt_correo, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                            .addComponent(lbl_log_email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_log_pass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPizquierdaLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jBLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPizquierdaLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPizquierdaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(IdLogeador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(104, 104, 104)
                .addComponent(jPImagenLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPizquierdaLayout.setVerticalGroup(
            jPizquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPizquierdaLayout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(lbl_log_email, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(lbl_log_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IdLogeador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPImagenLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPizquierda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPizquierda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_correoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_correoMousePressed
        txt_correo.setText("");
    }//GEN-LAST:event_txt_correoMousePressed

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void jLSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLSalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLSalirMouseClicked

    private void txt_passwordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_passwordMousePressed
        txt_password.setText("");
    }//GEN-LAST:event_txt_passwordMousePressed

    private void jLSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLSalirMouseEntered
        // TODO add your handling code here:
        jLSalir.setBackground(Color.red);
    }//GEN-LAST:event_jLSalirMouseEntered

    private void jBLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLoginActionPerformed
        if (validateLogin()) {
            login();
        }
        
        
    }//GEN-LAST:event_jBLoginActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Altausuario us = new Altausuario();
        us.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField IdLogeador;
    private javax.swing.JButton jBLogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLSalir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPImagenLateral;
    private javax.swing.JPanel jPizquierda;
    public javax.swing.JLabel lbl_log_email;
    private javax.swing.JLabel lbl_log_pass;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JPasswordField txt_password;
    // End of variables declaration//GEN-END:variables
}
