/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.CifradoHash;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tboss
 */
public class UserPanel extends javax.swing.JFrame {

    int idUserPanel = 0;

    /**
     * Creates new form UserPanel
     */
    public UserPanel(int idUsuarioUpanel) {
        initComponents();
        this.setResizable(true);
        this.setLocationRelativeTo(this);
        idUserPanel = idUsuarioUpanel;
        PVerMiscompras.setVisible(false);
    }

    public UserPanel() {
        initComponents();
        this.setResizable(true);
        this.setLocationRelativeTo(this);
        PVerMiscompras.setVisible(false);
    }

    Connection con = ConexionDB.Conexion.getConnection();
    PreparedStatement ps;
    ResultSet rs;
    int fila = 0;
    double total = 0.00;
    Home h = new Home();
    int datoseelcionado = 0;
    int dato_compoente = 0;
    int comprarealizada = 0;
    int FacturaSelecionada = 0;
    int TotalFactura = 0;
    int txtidFactura=0;

    // pasamos el id del usuario medainte parametro
    public void consultaboxMiCompra(int idUserPanel) {
        //realizamos la consulta de nuestra base de datos de usuarios y nuestra venta
        String insert = ("select id_user,id, idUsuario, fecha \n"
                + "from user, prueba1\n"
                + "where (user.id_user=prueba1.idUsuario) and id_user=" + idUserPanel); //donde sea el id del usuario recibido del parametro
        try {
            // realizamos la consulta
            ps = con.prepareStatement(insert);
            System.out.println(ps);
            rs = ps.executeQuery();
            while (rs.next()) {
                // en el combo box vermeos la fecha de la compra, de nuestro usuario
                ComboComprado.addItem(rs.getString("fecha"));
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    public boolean updateUserAcount() {
        Boolean isUpdated = false;
        //creamos unas variables para conseguir los datos y visualizarlos
        String unombre = txt_updnombre.getText();
        String uapellido = txt_updapellidos.getText();
        String upass = new String(txt_updpass.getPassword());
        String upss2 = new String(txt_updpass2.getPassword());
        String utelefono = txt_updtelefono.getText();
        String udireccion = txt_upddireccion.getText();
        //creamos una variable tipo texto y lo igualamos a "lo que contiene el if"

        try {
            if (upass.equals(upss2)) { //comparamos las contraseñas 
                Connection con = ConexionDB.Conexion.getConnection();
                // creamos una variable llamada nuevaContra y lo igualamos a las contraseña ya que si se cumple la condicion se almaena en la nueva variable

                //String nuevaContra = CifradoHash.sha1(upass);
                String nuevaContra = upass;
                String sql = "update user set nombre= ?,apellidos= ?,pass=?, telefono= ?,direccioncasa= ? where id_user=" + idUserPanel;
                System.out.println(sql);
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, unombre);
                pst.setString(2, uapellido);
                pst.setString(3, nuevaContra);
                pst.setString(4, utelefono);
                pst.setString(5, udireccion);
                int rowCount = pst.executeUpdate();

                if (rowCount > 0) {
                    isUpdated = true;
                } else {
                    isUpdated = false;
                }

            } else {
                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");
            }

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        return isUpdated;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BModificarDatos = new javax.swing.JButton();
        BVerComprasRealizadas = new javax.swing.JButton();
        BUserVolverHome = new javax.swing.JButton();
        BackgroundContenidoUser = new javax.swing.JPanel();
        PVerMiscompras = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaMiFactura = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        ComboComprado = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtTotalFactura = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_idFactura = new javax.swing.JTextField();
        PModificardatos = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_updapellidos = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_updpass2 = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        txt_upddireccion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_updnombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_updpass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        txt_updtelefono = new javax.swing.JTextField();
        jBCargarDatosUser = new javax.swing.JButton();
        ModificarDatosUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BModificarDatos.setText("Modificar Datos del Perfil");
        BModificarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BModificarDatosActionPerformed(evt);
            }
        });

        BVerComprasRealizadas.setText("Productos Comprados");
        BVerComprasRealizadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BVerComprasRealizadasActionPerformed(evt);
            }
        });

        BUserVolverHome.setText("Volver a ver mas productos");
        BUserVolverHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUserVolverHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BModificarDatos)
                .addGap(18, 18, 18)
                .addComponent(BVerComprasRealizadas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BUserVolverHome)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BModificarDatos)
                    .addComponent(BVerComprasRealizadas)
                    .addComponent(BUserVolverHome))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTablaMiFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablaMiFactura);

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setText("Selecione la fecha de su compra");

        ComboComprado.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ComboComprado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione su venta" }));
        ComboComprado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboCompradoItemStateChanged(evt);
            }
        });
        ComboComprado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboCompradoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jLabel11.setText("Total € :");

        txtTotalFactura.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jLabel12.setText("Codigo de su compra");

        txt_idFactura.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        javax.swing.GroupLayout PVerMiscomprasLayout = new javax.swing.GroupLayout(PVerMiscompras);
        PVerMiscompras.setLayout(PVerMiscomprasLayout);
        PVerMiscomprasLayout.setHorizontalGroup(
            PVerMiscomprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PVerMiscomprasLayout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(41, 41, 41)
                .addComponent(ComboComprado, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(602, 602, 602))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PVerMiscomprasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotalFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
            .addGroup(PVerMiscomprasLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(PVerMiscomprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(PVerMiscomprasLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(txt_idFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(93, 93, 93))
        );
        PVerMiscomprasLayout.setVerticalGroup(
            PVerMiscomprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PVerMiscomprasLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(PVerMiscomprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboComprado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(PVerMiscomprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_idFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(PVerMiscomprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Apellidos");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Repetir Contraseña");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Modifica Ubicacion/Dirrecion");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Datos de mi cuenta");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Nueva Contraseña ");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Telefono Movil");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_updtelefono)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_updnombre)
                                    .addComponent(jLabel4))
                                .addGap(125, 125, 125))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txt_updpass)
                        .addGap(131, 131, 131)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_upddireccion)
                            .addComponent(jLabel10)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txt_updpass2, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                                .addGap(4, 4, 4))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txt_updapellidos)
                        .addGap(4, 4, 4)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(109, 109, 109)
                        .addComponent(jLabel9)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_updpass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_updpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addComponent(jLabel10)
                        .addGap(48, 48, 48)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_upddireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_updtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_updnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_updapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addComponent(jLabel4)
                        .addGap(110, 110, 110)
                        .addComponent(jLabel5)
                        .addGap(80, 80, 80)))
                .addGap(77, 77, 77))
        );

        jBCargarDatosUser.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jBCargarDatosUser.setText("Cargar datos");
        jBCargarDatosUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCargarDatosUserActionPerformed(evt);
            }
        });

        ModificarDatosUsuario.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ModificarDatosUsuario.setText("Gurardar datos Actualizados");
        ModificarDatosUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarDatosUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PModificardatosLayout = new javax.swing.GroupLayout(PModificardatos);
        PModificardatos.setLayout(PModificardatosLayout);
        PModificardatosLayout.setHorizontalGroup(
            PModificardatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PModificardatosLayout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addGroup(PModificardatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PModificardatosLayout.createSequentialGroup()
                        .addComponent(jBCargarDatosUser, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ModificarDatosUsuario))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(293, 293, 293))
        );
        PModificardatosLayout.setVerticalGroup(
            PModificardatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PModificardatosLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(PModificardatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCargarDatosUser)
                    .addComponent(ModificarDatosUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout BackgroundContenidoUserLayout = new javax.swing.GroupLayout(BackgroundContenidoUser);
        BackgroundContenidoUser.setLayout(BackgroundContenidoUserLayout);
        BackgroundContenidoUserLayout.setHorizontalGroup(
            BackgroundContenidoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundContenidoUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PModificardatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(BackgroundContenidoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundContenidoUserLayout.createSequentialGroup()
                    .addComponent(PVerMiscompras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        BackgroundContenidoUserLayout.setVerticalGroup(
            BackgroundContenidoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundContenidoUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PModificardatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(BackgroundContenidoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PVerMiscompras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BackgroundContenidoUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BackgroundContenidoUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void BUserVolverHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUserVolverHomeActionPerformed
        // TODO add your handling code here:
        Home h = new Home(idUserPanel);
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BUserVolverHomeActionPerformed

    private void ModificarDatosUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarDatosUsuarioActionPerformed
        // TODO add your handling code here:
        if (updateUserAcount() == true) { // llamamos al metodo actualizar y lo comparamos
            JOptionPane.showMessageDialog(this, "contenido actualizado");
        } else {
            JOptionPane.showMessageDialog(this, "contenido no actualizado");
        }
    }//GEN-LAST:event_ModificarDatosUsuarioActionPerformed

    private void jBCargarDatosUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCargarDatosUserActionPerformed
        // TODO add your handling code here:
        Connection con = ConexionDB.Conexion.getConnection();
        PreparedStatement ps = null;
        ResultSet rs = null;
        // cargamos los datos del usuario 
        try {
            ps = con.prepareStatement("select nombre,apellidos,pass, telefono,direccioncasa from user where id_user =" + idUserPanel);
            System.out.println(ps);
            rs = ps.executeQuery();

            if (rs.next()) {
                txt_updnombre.setText(rs.getString("nombre"));
                txt_updapellidos.setText(rs.getString("apellidos"));
                txt_updpass.setText(rs.getString("pass"));
                txt_updtelefono.setText(rs.getString("telefono"));
                txt_upddireccion.setText(rs.getString("direccioncasa"));
            }
        } catch (Exception e) {
            e.getMessage();
        }

        /*try {
            ps = con.prepareStatement("select * from user where id_user = ?" +idUserPanel);
            ps.setString(1, txtUserEmail.getText());
            if (!"".equals(txtUserEmail.getText())) {
                //pasamos los del usuario para que se rellene el conenido, 
                rs = ps.executeQuery();
                if (rs.next()) {
                    // pasamos los contenidos de nuestra base de datos con nuestros campos
                    // ya que si no, a la hora de actualizar el dato quedaria a vacio
                    txt_updnombre.setText(rs.getString("nombre"));
                    txt_updapellidos.setText(rs.getString("apellidos"));
                    txt_updtelefono.setText(rs.getString("telefono"));
                    txt_upddireccion.setText(rs.getString("direccioncasa"));
                    //txt_updpass.setText(rs.getString("pass"));
                    //txt_updpass2.setText(rs.getString("pass"));       
                } else {
                    JOptionPane.showMessageDialog(null, "Introduce tu correo para poder modificar tus datos");

                }
            }
        } catch (Exception e) {
            e.getMessage();
        }*/
    }//GEN-LAST:event_jBCargarDatosUserActionPerformed

    private void BVerComprasRealizadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BVerComprasRealizadasActionPerformed
        PVerMiscompras.setVisible(true);
        PModificardatos.setVisible(false);
        consultaboxMiCompra(idUserPanel);
    }//GEN-LAST:event_BVerComprasRealizadasActionPerformed

    private void BModificarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BModificarDatosActionPerformed
        // TODO add your handling code here:
        PVerMiscompras.setVisible(false);
        PModificardatos.setVisible(true);
    }//GEN-LAST:event_BModificarDatosActionPerformed

    private void ComboCompradoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboCompradoItemStateChanged
        // TODO add your handling code here:
        String seleciontusuario = (String) ComboComprado.getSelectedItem();//igualamos los items de nuestro combo a una variable string
        Connection con = ConexionDB.Conexion.getConnection();
        PreparedStatement ps;
        ResultSet rs;
        //realizamos la consulta de nuestra tabla venta donde combo selecionado
        String sql = "select id from prueba1 where fecha='" + seleciontusuario + "';";
        try {
            //realizamos la consulta
            ps = con.prepareStatement(sql);
            //ejecutamos la consulta
            rs = ps.executeQuery();
            if (rs.next()) {
                // y devolvemos el id selecionado
                comprarealizada = rs.getInt("id");
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        //JOptionPane.showMessageDialog(null, "El id del combo principal es " + comprarealizada);
    }//GEN-LAST:event_ComboCompradoItemStateChanged

    private void ComboCompradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboCompradoActionPerformed
        // TODO add your handling code here:
        int totaldeFactura = 0;
        // cuando realizamos la acion del clicar en nuestro combo box  veremos si hay item selecionado 
        if (ComboComprado.getSelectedIndex() > 0) {
            // en caso de que haya selecionado pasara a realizar lo que queremos

            //creamos un metodo y se lo pasamos a nuestra tabla
            DefaultTableModel modelo = new DefaultTableModel();
            jTablaMiFactura.setModel(modelo);
            //realizamos la consulta de nuestras 2 tablas, en el cual selecionamos el id -- donde nuestro combo box estuvo selecionado
            String sql = "SELECT id, total, fecha, nombre, precio,cantidad, etadoactual\n" +
                    " FROM prueba1 C, prueba2 O, tipo_estado E WHERE (C.id = O.id_prueba1 AND O.estado = E.id_estado) and C.id=" + comprarealizada;
            try {
                //procedemos con la conexion a nuestra consulta
                ps = con.prepareStatement(sql);
                // procedemos a realizar la consulta
                System.out.println(ps);
                rs = ps.executeQuery();

                //result set para la tabla
                // aqui lo que hacemos es pasarle el resultado de la consulta
                ResultSetMetaData rsMd = rs.getMetaData();
                int cantidadColumnas = rsMd.getColumnCount();
                // creamos columnas
                modelo.addColumn("Nombre");
                modelo.addColumn("Precio");
                modelo.addColumn("Cantidad");
                modelo.addColumn("Estado");
                while (rs.next()) {
                    txtidFactura = rs.getInt("id");
                    totaldeFactura = rs.getInt("total");
                    Object filas[] = new Object[7];
                    filas[0] = rs.getObject(4);
                    filas[1] = rs.getObject(5);
                    filas[2] = rs.getObject(6);
                    filas[3] = rs.getObject(7);
                    modelo.addRow(filas);
                }

            } catch (Exception e) {
            }
            txt_idFactura.setEditable(false);
            txt_idFactura.setText(String.valueOf(txtidFactura));
            txtTotalFactura.setEditable(false);
            txtTotalFactura.setText(String.valueOf(totaldeFactura));
            System.out.println(totaldeFactura);
        } else {
            jTablaMiFactura.removeAll();
        }
    }//GEN-LAST:event_ComboCompradoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BModificarDatos;
    private javax.swing.JButton BUserVolverHome;
    private javax.swing.JButton BVerComprasRealizadas;
    private javax.swing.JPanel BackgroundContenidoUser;
    private javax.swing.JComboBox<String> ComboComprado;
    private javax.swing.JButton ModificarDatosUsuario;
    private javax.swing.JPanel PModificardatos;
    private javax.swing.JPanel PVerMiscompras;
    private javax.swing.JButton jBCargarDatosUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablaMiFactura;
    private javax.swing.JTextField txtTotalFactura;
    private javax.swing.JTextField txt_idFactura;
    private javax.swing.JTextField txt_updapellidos;
    private javax.swing.JTextField txt_upddireccion;
    private javax.swing.JTextField txt_updnombre;
    private javax.swing.JPasswordField txt_updpass;
    private javax.swing.JPasswordField txt_updpass2;
    private javax.swing.JTextField txt_updtelefono;
    // End of variables declaration//GEN-END:variables
}
